export default {
  SIGN_IN: "SIGN_IN",
  ANIMAL_LOCATION: "ANIMAL_LOCATION",
  REPORTED_ANIMAL_DETAILS: "REPORTED_ANIMAL_DETAILS",
  ANIMAL_ADOPTION: "ANIMAL_ADOPTION",
  USER_ACCOUNT: "USER_ACCOUNT",
  MENU_MORE_OPTIONS: "MENU_MORE_OPTIONS",
}
